// <auto-generated />
using System;
using AutoLegalTracker_API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoLegalTracker_API._3_DataAccess.Migrations
{
    [DbContext(typeof(ALTContext))]
    [Migration("20230915220909_12_Database_models")]
    partial class _12_Database_models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoLegalTracker_API.Models.CourtOrderRequested", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedCourtOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedCourtOrderId");

                    b.ToTable("CourtOrderRequested");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.CourtOrderSent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SentCourtOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SentCourtOrderId");

                    b.ToTable("CourtOrderSent");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EmailDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmailTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("UserTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emailCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalAutomation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CaseCaptionContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseCaptionDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExpenseAdvancesPaid")
                        .HasColumnType("bit");

                    b.Property<string>("JurisdictionContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JurisdictionDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationBodyContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationBodyDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationFromContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationFromDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationToContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationToDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RunsAutomatically")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LegalAutomations");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExpenseAdvancesPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PossibleCourtDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LegalCases");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegalCaseAttributeConditionId")
                        .HasColumnType("int");

                    b.Property<int>("LegalCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseAttributeConditionId");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("LegalCaseAttribute");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAttributeCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegalCaseAttributeConditionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseAttributeConditionId");

                    b.ToTable("LegalCaseAttributeCondition");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValueType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LegalCaseProperty");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegalAutomationId")
                        .HasColumnType("int");

                    b.Property<int>("LegalCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalAppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseAutomation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LegalAutomationId");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("LegalNotifications");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.MedicalAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegalNotificationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PatientAttended")
                        .HasColumnType("bit");

                    b.Property<bool?>("PatientAttendedOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegalNotificationId")
                        .IsUnique();

                    b.ToTable("MedicalAppointments");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.RequestedAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegalCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("RequestedAnalysis");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleOAuth2AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleOAuth2IdToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleOAuth2RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GoogleOAuth2TokenCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("GoogleOAuth2TokenExpiration")
                        .HasColumnType("bigint");

                    b.Property<string>("GoogleProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebCredentialPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebCredentialUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("LegalCaseAttributeConditionLegalCaseProperty", b =>
                {
                    b.Property<int>("LegalCaseAttributeConditionsId")
                        .HasColumnType("int");

                    b.Property<int>("LegalCasePropertiesId")
                        .HasColumnType("int");

                    b.HasKey("LegalCaseAttributeConditionsId", "LegalCasePropertiesId");

                    b.HasIndex("LegalCasePropertiesId");

                    b.ToTable("LegalCaseAttributeConditionLegalCaseProperty");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.CourtOrderRequested", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", "RequestedCourtOrder")
                        .WithMany("RequestedCourtOrders")
                        .HasForeignKey("RequestedCourtOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedCourtOrder");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.CourtOrderSent", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", "SentCourtOrder")
                        .WithMany("SentCourtOrders")
                        .HasForeignKey("SentCourtOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SentCourtOrder");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailLog", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.EmailTemplate", "Email")
                        .WithMany("EmailLogs")
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalAutomation", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCase", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.User", "User")
                        .WithMany("LegalCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAttribute", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAttributeCondition", "LegalCaseAttributeCondition")
                        .WithMany("LegalCaseAttributes")
                        .HasForeignKey("LegalCaseAttributeConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", "LegalCase")
                        .WithMany("LegalCaseAttributes")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalCase");

                    b.Navigation("LegalCaseAttributeCondition");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAttributeCondition", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAttributeCondition", null)
                        .WithMany("LegalCaseAttributeConditionsToCheck")
                        .HasForeignKey("LegalCaseAttributeConditionId");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalNotification", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalAutomation", "LegalAutomation")
                        .WithMany("LegalNotifications")
                        .HasForeignKey("LegalAutomationId");

                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", "LegalCase")
                        .WithMany("LegalNotifications")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalAutomation");

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.MedicalAppointment", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalNotification", "LegalNotification")
                        .WithOne("MedicalAppointment")
                        .HasForeignKey("AutoLegalTracker_API.Models.MedicalAppointment", "LegalNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalNotification");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.RequestedAnalysis", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", null)
                        .WithMany("RequestedAnalyses")
                        .HasForeignKey("LegalCaseId");
                });

            modelBuilder.Entity("LegalCaseAttributeConditionLegalCaseProperty", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAttributeCondition", null)
                        .WithMany()
                        .HasForeignKey("LegalCaseAttributeConditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseProperty", null)
                        .WithMany()
                        .HasForeignKey("LegalCasePropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailTemplate", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalAutomation", b =>
                {
                    b.Navigation("LegalNotifications");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCase", b =>
                {
                    b.Navigation("LegalCaseAttributes");

                    b.Navigation("LegalNotifications");

                    b.Navigation("RequestedAnalyses");

                    b.Navigation("RequestedCourtOrders");

                    b.Navigation("SentCourtOrders");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAttributeCondition", b =>
                {
                    b.Navigation("LegalCaseAttributeConditionsToCheck");

                    b.Navigation("LegalCaseAttributes");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalNotification", b =>
                {
                    b.Navigation("MedicalAppointment")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.User", b =>
                {
                    b.Navigation("LegalCases");
                });
#pragma warning restore 612, 618
        }
    }
}
