// <auto-generated />
using System;
using AutoLegalTracker_API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoLegalTracker_API._3_DataAccess.Migrations
{
    [DbContext(typeof(ALTContext))]
    [Migration("20231003110652_12_Database_models")]
    partial class _12_Database_models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EmailDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmailTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("UserTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emailCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalAutomation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CaseCaptionContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseCaptionDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExpenseAdvancesPaid")
                        .HasColumnType("bit");

                    b.Property<string>("JurisdictionContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JurisdictionDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationBodyContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationBodyDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationFromContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationFromDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationToContains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationToDoesNotContain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RunsAutomatically")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LegalAutomations");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExpenseAdvances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ExpenseAdvancesPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastScrappedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LegalCaseHonorarium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PossibleCourtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScrapUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LegalCases");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AssignMedicalAppointment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmailTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("LegalCaseConditionId")
                        .HasColumnType("int");

                    b.Property<int?>("LegalResponseTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotificationConditionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.HasIndex("LegalCaseConditionId");

                    b.HasIndex("LegalResponseTemplateId");

                    b.HasIndex("NotificationConditionId");

                    b.HasIndex("UserId");

                    b.ToTable("LegalCaseActions");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AttributeToAddWhenExpiredId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LegalCaseConditionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttributeToAddWhenExpiredId");

                    b.HasIndex("LegalCaseConditionId");

                    b.ToTable("LegalCaseAttributes");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AnalysesMustBeReceived")
                        .HasColumnType("bit");

                    b.Property<string>("CaseCaptionContains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseCaptionDoesNotContain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExpensesShouldBePaid")
                        .HasColumnType("bit");

                    b.Property<string>("JurisdictionContains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JurisdictionDoesNotContain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequestedCourtOrdersMustBeReceived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LegalCaseConditions");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ActionHasBeenTaken")
                        .HasColumnType("bit");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegalAutomationId")
                        .HasColumnType("int");

                    b.Property<int>("LegalCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalAppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("ScrapUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Signed")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegalAutomationId");

                    b.HasIndex("LegalCaseId");

                    b.HasIndex("MedicalAppointmentId")
                        .IsUnique()
                        .HasFilter("[MedicalAppointmentId] IS NOT NULL");

                    b.ToTable("LegalNotifications");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalResponseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LegalResponseTemplate");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.MedicalAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegalNotificationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PatientAttended")
                        .HasColumnType("bit");

                    b.Property<bool?>("PatientAttendedOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MedicalAppointments");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.NotificationCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BodyContains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyDoesNotContain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromContains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromDoesNotContain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleContains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDoesNotContain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToContains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDoesNotContain")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationConditions");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.NotificationReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegalNotificationId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LegalNotificationId");

                    b.ToTable("NotificationReferences");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.RequestedAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit");

                    b.Property<int>("LegalCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("RequestedAnalyses");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.RequestedCourtOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit");

                    b.Property<int>("LegalCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("RequestedCourtOrders");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleOAuth2AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleOAuth2IdToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleOAuth2RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GoogleOAuth2TokenCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("GoogleOAuth2TokenExpiration")
                        .HasColumnType("bigint");

                    b.Property<string>("GoogleProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastScrappedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastScrappedPage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("WebCredentialPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebCredentialUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegalCaseActionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseActionId");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("LegalCaseAttributesToAdd", b =>
                {
                    b.Property<int>("LegalCaseActionsWhereItsAddedId")
                        .HasColumnType("int");

                    b.Property<int>("LegalCaseAttributesToAddId")
                        .HasColumnType("int");

                    b.HasKey("LegalCaseActionsWhereItsAddedId", "LegalCaseAttributesToAddId");

                    b.HasIndex("LegalCaseAttributesToAddId");

                    b.ToTable("LegalCaseAttributesToAdd");
                });

            modelBuilder.Entity("LegalCaseAttributesToDelete", b =>
                {
                    b.Property<int>("LegalCaseActionsWhereItsDeletedId")
                        .HasColumnType("int");

                    b.Property<int>("LegalCaseAttributesToDeleteId")
                        .HasColumnType("int");

                    b.HasKey("LegalCaseActionsWhereItsDeletedId", "LegalCaseAttributesToDeleteId");

                    b.HasIndex("LegalCaseAttributesToDeleteId");

                    b.ToTable("LegalCaseAttributesToDelete");
                });

            modelBuilder.Entity("LegalCaseLegalCaseAttribute", b =>
                {
                    b.Property<int>("LegalCaseAttributesId")
                        .HasColumnType("int");

                    b.Property<int>("LegalCaseId")
                        .HasColumnType("int");

                    b.HasKey("LegalCaseAttributesId", "LegalCaseId");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("LegalCaseLegalCaseAttribute");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailLog", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.EmailTemplate", "EmailTemplate")
                        .WithMany("EmailLogs")
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailTemplate");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalAutomation", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCase", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.User", "User")
                        .WithMany("LegalCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAction", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.EmailTemplate", "EmailTemplate")
                        .WithMany()
                        .HasForeignKey("EmailTemplateId");

                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseCondition", "LegalCaseCondition")
                        .WithMany()
                        .HasForeignKey("LegalCaseConditionId");

                    b.HasOne("AutoLegalTracker_API.Models.LegalResponseTemplate", "LegalResponseTemplate")
                        .WithMany()
                        .HasForeignKey("LegalResponseTemplateId");

                    b.HasOne("AutoLegalTracker_API.Models.NotificationCondition", "NotificationCondition")
                        .WithMany()
                        .HasForeignKey("NotificationConditionId");

                    b.HasOne("AutoLegalTracker_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmailTemplate");

                    b.Navigation("LegalCaseCondition");

                    b.Navigation("LegalResponseTemplate");

                    b.Navigation("NotificationCondition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAttribute", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAttribute", "AttributeToAddWhenExpired")
                        .WithMany()
                        .HasForeignKey("AttributeToAddWhenExpiredId");

                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseCondition", null)
                        .WithMany("LegalCaseAttributes")
                        .HasForeignKey("LegalCaseConditionId");

                    b.Navigation("AttributeToAddWhenExpired");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalNotification", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalAutomation", null)
                        .WithMany("LegalNotifications")
                        .HasForeignKey("LegalAutomationId");

                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", "LegalCase")
                        .WithMany("LegalNotifications")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoLegalTracker_API.Models.MedicalAppointment", "MedicalAppointment")
                        .WithOne("LegalNotification")
                        .HasForeignKey("AutoLegalTracker_API.Models.LegalNotification", "MedicalAppointmentId");

                    b.Navigation("LegalCase");

                    b.Navigation("MedicalAppointment");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.NotificationReference", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalNotification", null)
                        .WithMany("NotificationReferences")
                        .HasForeignKey("LegalNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.RequestedAnalysis", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", "LegalCase")
                        .WithMany("RequestedAnalyses")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.RequestedCourtOrder", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", "LegalCase")
                        .WithMany("RequestedCourtOrders")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.User", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.UserType", "userType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userType");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.UserType", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAction", null)
                        .WithMany("UserTypes")
                        .HasForeignKey("LegalCaseActionId");
                });

            modelBuilder.Entity("LegalCaseAttributesToAdd", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAction", null)
                        .WithMany()
                        .HasForeignKey("LegalCaseActionsWhereItsAddedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAttribute", null)
                        .WithMany()
                        .HasForeignKey("LegalCaseAttributesToAddId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegalCaseAttributesToDelete", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAction", null)
                        .WithMany()
                        .HasForeignKey("LegalCaseActionsWhereItsDeletedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAttribute", null)
                        .WithMany()
                        .HasForeignKey("LegalCaseAttributesToDeleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegalCaseLegalCaseAttribute", b =>
                {
                    b.HasOne("AutoLegalTracker_API.Models.LegalCaseAttribute", null)
                        .WithMany()
                        .HasForeignKey("LegalCaseAttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoLegalTracker_API.Models.LegalCase", null)
                        .WithMany()
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.EmailTemplate", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalAutomation", b =>
                {
                    b.Navigation("LegalNotifications");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCase", b =>
                {
                    b.Navigation("LegalNotifications");

                    b.Navigation("RequestedAnalyses");

                    b.Navigation("RequestedCourtOrders");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseAction", b =>
                {
                    b.Navigation("UserTypes");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalCaseCondition", b =>
                {
                    b.Navigation("LegalCaseAttributes");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.LegalNotification", b =>
                {
                    b.Navigation("NotificationReferences");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.MedicalAppointment", b =>
                {
                    b.Navigation("LegalNotification")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.User", b =>
                {
                    b.Navigation("LegalCases");
                });

            modelBuilder.Entity("AutoLegalTracker_API.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
